version: 0
metadata:
  name: Balrogworker Image Creation
  description: Funsize Submission to Balrog
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 2400
      image: "taskcluster/image_builder:0.1.3"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd funsize-balrogworker && git checkout $GITHUB_HEAD_BRANCH && \
           ./tc_testbuild.sh"
      features:
        dind: true
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
    metadata:
      name: Balrogworker Tests
      description: Balrogworker Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

# TODO: make this depend on the test task after https://bugzilla.mozilla.org/show_bug.cgi?id=1252144 is fixed
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 3600
      image: "taskcluster/image_builder:0.1.3"
      features:
        dind: true
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd funsize-balrogworker && git checkout $GITHUB_HEAD_BRANCH && \
           ./tc_build.sh"
    scopes:
      - secrets:get:repo:github.com/mozilla-releng/funsize-balrogworker:branch:master
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
    metadata:
      name: Balrogworker Docker Image Creation
      description: Funsize Balrogworker Docker Image Creation
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"